### ISSUE TITLE
Add image for NFT field back in

### ISSUE THREAD

**Issue by RadarDAO** [RadarDAO-xyz/radar-launch-frontend#137]
Add a field in the submission form where a user can upload a file for the NFT.

If they don't upload an image it takes the thumbnail of the video.

Please add the copy.

`Please upload an image to represent your project, make it authentic.

This will appear for collectors in their wallet and on their profile

Note: you can leave this empty and this image will be taken from the thumbnail of your uploaded video.`

<img width="829" alt="Screenshot 2023-08-08 at 15 09 55" src="https://github.com/RadarDAO-xyz/radar-launch-frontend/assets/103267267/fdd88a6f-ce3c-453e-898e-412760a68b00">

**Comment by mrTomatolegit** [comment]
BE should now support image thumbnail uploads on post and patch, view postman docs for example
Field name is `thumbnail` and defaults to the `video_url` thumbnail

Ready for FE implementation and testing

**Comment by marcuspang** [comment]
@kevincompton could you make the UI for this file submission? You can copy over the `<Input type='file"/>` component inside the `/profile/[id]/edit` page. Just have to make it square and centralise the text.

If you have time you could replicate the `new FormData()` method, otherwise you can leave it once you're done with the UI

**Comment by marcuspang** [comment]
This is /project/create page
